DROP TABLE IF EXISTS t_author;
DROP SEQUENCE IF EXISTS SEQ_ID;

CREATE SEQUENCE SEQ_ID START WITH 3 INCREMENT BY 1;
CREATE TABLE t_author (
  id BIGINT NOT NULL,
  name VARCHAR(32) NOT NULL,
  age INT,
  CONSTRAINT PK PRIMARY KEY (id)
);
